export const INITIAL_TODO_DATA = { title: '', completed: false, isEdit: true };
export const HTTP_METHOD = {
	GET: 'GET',
	POST: 'POST',
	PATCH: 'PATCH',
	DELETE: 'DELETE',
};

export const TODO_ACTIONS = {
	GET_ALL_TODOS: 'GET_ALL_TODOS',
	GET_TODO: 'GET_TODO',
	ADD_TODO: 'ADD_TODO',
	UPDATE_TODO: 'UPDATE_TODO',
	TODO_COMPLETED: 'TODO_COMPLETED',
	DELETE_TODO: 'DELETE_TODO',
	SORT_TODOS: 'SORT_TODOS',
	SEARCH: 'SEARCH',
};

export const OPTION_ACTIONS = {
	LOADING_START: 'LOADING_START',
	LOADING_FINISH: 'LOADING_FINISH',
	UPDATE_ROOT_CLASSNAME: 'UPDATE_ROOT_CLASSNAME',
	SET_USER_SEARCH: 'SET_USER_SEARCH',
};
